#version 450

struct Face
{
    vec3 Verts[40];
    uint NumVerts;
};

struct Cell {
    Face Faces[40];
    uint NumFaces;
};


layout(std430, binding = 1) readonly buffer VoronoiSSBOIn {
    vec3 Points[100];
    uint NumPoints;
    Face BoundingBoxFaces[6];
};

layout(std430, binding = 3) buffer VoronoiSSBOOut
{ 
    uint NumCells;
    uint DebugNum;
    Cell CutCells[100];
};

layout(std430, binding = 6) buffer VoronoiWorkingBuffer
{
    Cell WorkingCells[100];
    Cell TempCells[100];
    Face IntersectFaces[100];
};

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void DefinePlane(const in vec3 CurrentPoint, const in vec3 ComparedPoint, out vec3 Normal, out vec3 Center)
{
    Normal = normalize(ComparedPoint - CurrentPoint);
    
    Center = (CurrentPoint + ComparedPoint) / 2;
}
bool AlmostEqual(vec3 a, vec3 b, float epsilon)
{
    return all(lessThanEqual(abs(a - b), vec3(epsilon)));
}

void AddFaceVert(inout Face InFace, const in vec3 Vert)
{
    InFace.Verts[InFace.NumVerts] = Vert;
    InFace.NumVerts++;
}

bool GetIntersectionPoint(const in vec3 Center, const in vec3 Normal, const in vec3 LineStart, const in vec3 LineDir, out vec3 IntersectionPoint)
{
    const float dot1 = dot(Normal, LineDir);
    
    if (dot1 == 0) return false;
    const float d = -dot(Normal, Center);
    const float dot2 = dot(Normal, LineStart);
    
    const float t = -(dot2 + d) / dot1;
    
    if (t < 0 || t > 1) return false;
    
    IntersectionPoint = LineStart + (t * LineDir);
    return true;
}


void GetFirstIntersection(const in vec3 Normal, const in vec3 Center, const in uint CurrentFace, 
inout uint FirstIntersectionIndex, out vec3 FirstIntersection, const in uint Index)
{
    TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts = 0;
    for (FirstIntersectionIndex; FirstIntersectionIndex < WorkingCells[Index].Faces[CurrentFace].NumVerts; FirstIntersectionIndex++)
    {
        const vec3 fromVert = WorkingCells[Index].Faces[CurrentFace].Verts[FirstIntersectionIndex];
        const vec3 toVert = WorkingCells[Index].Faces[CurrentFace].Verts[(FirstIntersectionIndex +1) % WorkingCells[Index].Faces[CurrentFace].NumVerts];
        
        const vec3 lineDir = toVert - fromVert;
        vec3 intersectionPoint;
        const bool bDoesLineIntersect = GetIntersectionPoint(Center, Normal, fromVert, lineDir, intersectionPoint);
        if (bDoesLineIntersect)
        {
            const bool bIsIntersectionNextVertex = AlmostEqual(intersectionPoint, toVert, 0.0001);
            if (bIsIntersectionNextVertex)
            {
                TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = toVert;
                TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
                TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = WorkingCells[Index].Faces[CurrentFace].Verts[(FirstIntersectionIndex + 2) % WorkingCells[Index].Faces[CurrentFace].NumVerts];
                TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
                FirstIntersectionIndex = (FirstIntersectionIndex + 2) % WorkingCells[Index].Faces[CurrentFace].NumVerts;

            }
            else
            {
                TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = intersectionPoint;
                TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
                TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = toVert;
                TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
                FirstIntersectionIndex = (FirstIntersectionIndex + 1) % WorkingCells[Index].Faces[CurrentFace].NumVerts;
            }
            FirstIntersection = intersectionPoint;
            break;
        }
    }
}

uint GetAllVertsUntillSecondIntersection(const in vec3 Normal, const in vec3 Center, const in uint ToClip, const in uint FirstIntersectionIndex, out vec3 SecondIntersection, const in uint Index)
{
    uint secondIntersectionIndex = 0;
    for (secondIntersectionIndex = FirstIntersectionIndex; secondIntersectionIndex <  WorkingCells[Index].Faces[ToClip].NumVerts; secondIntersectionIndex++)
    {
        const vec3 fromVert =  WorkingCells[Index].Faces[ToClip].Verts[secondIntersectionIndex];
        const vec3 toVert =  WorkingCells[Index].Faces[ToClip].Verts[(secondIntersectionIndex + 1) %  WorkingCells[Index].Faces[ToClip].NumVerts];

        const vec3 lineDir = toVert - fromVert;
        vec3 intersectionPoint;
        const bool bDoesLineIntersect = GetIntersectionPoint(Center, Normal, fromVert, lineDir, intersectionPoint);
        
        if (bDoesLineIntersect)
        {
            TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = intersectionPoint;
            TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
            SecondIntersection = intersectionPoint;
            secondIntersectionIndex++;
            break;
        }
        TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = toVert;
        TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
    }
    return secondIntersectionIndex;
}

bool isNearlyZero(const in float X)
{
    return X < 1e-6 && X > -1e-6;
}

bool IsPointInPolyhedra(const in vec3 Normal, const in uint Index, const in vec3 Center, const in uint CutTIme, const in uint Plane)
{
    for (uint i = 0; i < TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts; i++)
    {
        const float d = dot(TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[i] - Center, Normal);
        if (d > 0 && !isNearlyZero(d))
        {
            return false;
        } 
    }
    return true;
}

void GetFaceReversed(const in uint ToClip, const in uint Index, const in uint FirstIntersectionIndex,
const in vec3 FirstIntersection, const in vec3 SecondIntersection, const in uint SecondInterectionIndex, const in uint CutTIme, const in uint Plane)
{
    TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts = 0;
    if (SecondIntersection !=  WorkingCells[Index].Faces[ToClip].Verts[SecondInterectionIndex %  WorkingCells[Index].Faces[ToClip].NumVerts])
    {
        TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = SecondIntersection;
        TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
    }
    vec3 from;
    for (uint i = SecondInterectionIndex; i %  WorkingCells[Index].Faces[ToClip].NumVerts != FirstIntersectionIndex; i++)
    {
        from =  WorkingCells[Index].Faces[ToClip].Verts[i %  WorkingCells[Index].Faces[ToClip].NumVerts];
        const vec3 to =  WorkingCells[Index].Faces[ToClip].Verts[(i+1) %  WorkingCells[Index].Faces[ToClip].NumVerts];
        if (AlmostEqual(from, to, 0.00001)) continue;
        TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = from;
        TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
    }
    if (!AlmostEqual(from, FirstIntersection, 0.00001))
    {
        TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = FirstIntersection;
        TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
    }
    
}

void ClipFacebyFace(const in uint ToClip, const in vec3 Center,const in uint Index, const in vec3 Normal, const in uint CutTimes, const in uint Plane)
{
    uint firstIntersectionIndex = 0;
    vec3 firstIntersection;
    GetFirstIntersection(Normal, Center, ToClip, firstIntersectionIndex, firstIntersection, Index);
       
    if (TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts == 0)
    {
        for (uint i = 0; i < WorkingCells[Index].Faces[ToClip].NumVerts; i++)
        {
            if (dot(Normal, WorkingCells[Index].Faces[ToClip].Verts[i] - Center) < 0)
            {
                TempCells[Index].Faces[TempCells[Index].NumFaces] =  WorkingCells[Index].Faces[ToClip];
                return;
            }
        }
        return;
    }
    vec3 secondIntersection;
    uint secondIntersectionIndex = GetAllVertsUntillSecondIntersection(Normal, Center, ToClip, firstIntersectionIndex, secondIntersection, Index);
    if (!IsPointInPolyhedra(Normal, Index, Center, CutTimes, Plane))
    {
        GetFaceReversed(ToClip, Index, firstIntersectionIndex, firstIntersection, secondIntersection, secondIntersectionIndex, CutTimes, Plane);
    }

    IntersectFaces[Index].Verts[IntersectFaces[Index].NumVerts] = firstIntersection;
    IntersectFaces[Index].NumVerts++;
    IntersectFaces[Index].Verts[IntersectFaces[Index].NumVerts] = secondIntersection;
    IntersectFaces[Index].NumVerts++;
    
}

void GetPlaneAxis(const in vec3 Normal, out vec3 T, out vec3 U)
{
    vec3 Up = vec3(0, 1, 0);
    if (abs(dot(Normal, Up)) > 0.99f) Up = vec3(1, 0, 0);
    U = normalize(cross(Normal, Up));
    T = cross(Normal, U);
}

void OrderByAngle(inout Face InFace, const in vec3 Center, const in vec3 Normal)
{
    vec3 t, u;
    GetPlaneAxis(Normal, t, u);
    
    float angles[40];
    for (uint i = 0; i < InFace.NumVerts; i++)
    {
        const vec3 d = InFace.Verts[i] - Center;
        const float x = dot(d, u);
        const float y = dot(d, t);
        angles[i] = atan(y, x);
    }
    Face newFace;
    newFace.NumVerts = 0;
    float nextAngle = 99999;
    uint nextAngleIndex;
    while (newFace.NumVerts < InFace.NumVerts)
    {
        for (uint i = 0; i < InFace.NumVerts; i++)
        {
            if (angles[i] <= nextAngle)
            {
                nextAngle = angles[i];
                nextAngleIndex = i;
            }
        }
        newFace.Verts[newFace.NumVerts] = InFace.Verts[nextAngleIndex];
        newFace.NumVerts++;
        angles[nextAngleIndex] = 99999;
        nextAngle = 9999;
    }
    
    InFace = newFace;
}
bool Contains(const in vec3 Item, const in Face InFace)
{
    for (uint i = 0; i < InFace.NumVerts; i++)
    {
        if (AlmostEqual(InFace.Verts[i], Item, 0.00001)) return true;
    }
    return false;
}

void RemoveDuplicates(const in uint Index)
{
    Face newFace;
    newFace.NumVerts = 0;
    for (uint i = 0; i < TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts; i++)
    {
        if (Contains(TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[i], newFace)) continue;

        newFace.Verts[newFace.NumVerts] =TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[i];
        newFace.NumVerts++;
    }
    TempCells[Index].Faces[TempCells[Index].NumFaces] = newFace;

}

void RemoveIntersectDuplicates(const in uint Index)
{
    Face newFace;
    newFace.NumVerts = 0;
    for (uint i = 0; i < IntersectFaces[Index].NumVerts; i++)
    {
        if (Contains(IntersectFaces[Index].Verts[i], newFace)) continue;

        newFace.Verts[newFace.NumVerts] = IntersectFaces[Index].Verts[i];
        newFace.NumVerts++;
    }
    IntersectFaces[Index] = newFace;

}

void RemoveAt(const in uint FaceIndex, const in uint Index)
{
    TempCells[FaceIndex].Faces[TempCells[FaceIndex].NumFaces].NumVerts--;
    for (uint i = Index; i < TempCells[FaceIndex].Faces[TempCells[FaceIndex].NumFaces].NumVerts; i++)
    {
        TempCells[FaceIndex].Faces[TempCells[FaceIndex].NumFaces].Verts[i] = TempCells[FaceIndex].Faces[TempCells[FaceIndex].NumFaces].Verts[(i+1)];
    }
}


void RemovePointsTooNear(const in uint Index)
{
    for (uint i = 0; i < TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts; i++)
    {
        if (distance(TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[i], TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[(i+1) % TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts]) < 1e-6)
        {
            RemoveAt(Index, i);
        }
    }
}

void IntersectRemoveAt(const in uint FaceIndex, const in uint Index)
{
    IntersectFaces[FaceIndex].NumVerts--;
    for (uint i = Index; i < IntersectFaces[FaceIndex].NumVerts; i++)
    {
        IntersectFaces[FaceIndex].Verts[i] = IntersectFaces[FaceIndex].Verts[(i+1)];
    }
}


void RemoveIntersectPointsTooNear(const in uint Index)
{
    for (uint i = 0; i < IntersectFaces[Index].NumVerts; i++)
    {
        if (distance(IntersectFaces[Index].Verts[i], IntersectFaces[Index].Verts[(i+1) % IntersectFaces[Index].NumVerts]) < 1e-6)
        {
            IntersectRemoveAt(Index, i);
        }
    }
}
vec3 GetPlaneCenter(const in Face Plane)
{
    vec3 center = vec3(0, 0, 0);
    for (uint i = 0; i < Plane.NumVerts; i++)
    {
        center += Plane.Verts[i];
    }
    return center / Plane.NumVerts;
}

void ClipCellByFace(const in uint Index, const in vec3 Center, const in vec3 Normal, const in uint CutTime)
{
    TempCells[Index].NumFaces = 0;
    IntersectFaces[Index].NumVerts = 0;
    
    for (uint i = 0; i <  WorkingCells[Index].NumFaces; i++)
    {
        TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts = 0;
        ClipFacebyFace(i, Center, Index, Normal, CutTime, TempCells[Index].NumFaces);

        if (TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts < 3) continue;

        RemoveDuplicates(Index);

        if (TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts < 3) continue;

        RemovePointsTooNear(Index);

        if (TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts < 3) continue;

        OrderByAngle(TempCells[Index].Faces[TempCells[Index].NumFaces], GetPlaneCenter(TempCells[Index].Faces[TempCells[Index].NumFaces]), Normal);

        TempCells[Index].NumFaces++;
    }
    if (IntersectFaces[Index].NumVerts >= 3)
    {
        OrderByAngle(IntersectFaces[Index], Center, Normal);

        RemoveIntersectDuplicates(Index);

        RemoveIntersectPointsTooNear(Index);
        
        if (IntersectFaces[Index].NumVerts >= 3)
        {
            TempCells[Index].Faces[TempCells[Index].NumFaces] = IntersectFaces[Index];
            TempCells[Index].NumFaces++;
        }
    }

    WorkingCells[Index] = TempCells[Index];
}


vec3 GetPlaneNormal(const in Face Plane, const in vec3 Center)
{
    vec3 normal = vec3(0, 0, 0);
    for (uint i = 0; i < Plane.NumVerts; i++)
    {
        const vec3 current = Plane.Verts[i];
        const vec3 next = Plane.Verts[(i+1) % Plane.NumVerts];

        normal.x += (current.y - next.y) * (current.z + next.z);
        normal.y += (current.z - next.z) * (current.x + next.x);
        normal.z += (current.x - next.x) * (current.y + next.y);
    }
    return normalize(normal);
}

void TriangulateRawCell(const in uint index)
{
    CutCells[index].NumFaces = 0;

    for (uint i = 0; i < WorkingCells[index].NumFaces; i++)
    {
        if ( WorkingCells[index].Faces[i].NumVerts < 3) continue;
        CutCells[index].Faces[CutCells[index].NumFaces].NumVerts = 0;
        for (uint j = 0; j <  WorkingCells[index].Faces[i].NumVerts; j++)
        {
            if (Contains( WorkingCells[index].Faces[i].Verts[j], CutCells[index].Faces[CutCells[index].NumFaces])) continue;
            AddFaceVert(CutCells[index].Faces[CutCells[index].NumFaces],  WorkingCells[index].Faces[i].Verts[j]);
        }

        if (CutCells[index].Faces[CutCells[index].NumFaces].NumVerts < 3) continue;
        vec3 center = GetPlaneCenter(CutCells[index].Faces[CutCells[index].NumFaces]);
        OrderByAngle(CutCells[index].Faces[CutCells[index].NumFaces], center, GetPlaneNormal(CutCells[index].Faces[CutCells[index].NumFaces], center));
        CutCells[index].NumFaces++;
    }
}


void main()
{
    uint index = gl_GlobalInvocationID.x;

    if (index >= NumPoints) return;
    
    vec3 point = Points[index];
    
    WorkingCells[index].NumFaces = 0;

    for (uint i = 0; i < 6; i++)
    {
        WorkingCells[index].Faces[WorkingCells[index].NumFaces] = BoundingBoxFaces[i];
        WorkingCells[index].NumFaces++;
    }
    
    for (uint i = 0; i < NumPoints; i++)
    {
        if (i == index) continue;
        const vec3 ComparedPoint = Points[i];
        vec3 normal, center;
        DefinePlane(point, ComparedPoint, normal, center);
        ClipCellByFace(index, center, normal, i);
    }
    CutCells[index] = WorkingCells[index];
    //TriangulateRawCell(index);
    atomicAdd(NumCells, 1);

}
