#version 450

struct Face
{
    vec3 Verts[40];
    uint NumVerts;
};

struct Cell {
    Face Faces[40];
    uint NumFaces;
};

struct RawCell
{
    vec3 Verts[1000];
    uint Inds[20000];
    uint NumInds;
    uint NumVerts;
};

struct TetFace
{
    vec3 Verts[3];
};

struct Tet
{
    TetFace Faces[4];
};

struct Box
{
    vec3 Min;
    vec3 Max;
};

layout(std430, binding = 3) buffer VoronoiSSBOOut
{ 
    uint NumCells;
    uint DebugNum;
    Cell CutCells[100];
};

layout(std430, binding = 4) buffer TetMeshIn
{
    uint NumTets;
    Tet[1000] Tets;
};

layout(std430, binding = 5) buffer ClippingSSBOOut
{
    uint NumCellsCut;
    uint DebugNum2;
    RawCell ClippedCells[100];
};


layout(std430, binding = 6) buffer VoronoiWorkingBuffer
{
    Cell WorkingCells[100];
    Cell TempCells[100];
    Face IntersectFaces[100];
};
//We dont need additonal invocations, as all tasks need to be done on a single thread in order
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;


bool AlmostEqual(vec3 a, vec3 b, float epsilon)
{
    return all(lessThanEqual(abs(a - b), vec3(epsilon)));
}
void DefinePlane(const in vec3 CurrentPoint, const in vec3 ComparedPoint, out vec3 Normal, out vec3 Center)
{
    Normal = normalize(ComparedPoint - CurrentPoint);
    
    Center = (CurrentPoint + ComparedPoint) / 2;
}

bool GetIntersectionPoint(const in vec3 Center, const in vec3 Normal, const in vec3 LineStart, const in vec3 LineDir, out vec3 IntersectionPoint)
{
    const float dot1 = dot(Normal, LineDir);
    //if they are perpendicular
    if (dot1 == 0) return false;
    const float d = -dot(Normal, Center);
    const float dot2 = dot(Normal, LineStart);
    
    const float t = -(dot2 + d) / dot1;
    //Outside of the lines length, t = distance along the line
    if (t < 0 || t > 1) return false;
    
    IntersectionPoint = LineStart + (t * LineDir);
    return true;
}


void GetFirstIntersection(const in vec3 Normal, const in vec3 Center, const in uint CurrentFace,
inout uint FirstIntersectionIndex, out vec3 FirstIntersection, const in uint Index)
{
    //Ensure the numVerts are reset to zero, should always be a new cell
    TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts = 0;
    for (FirstIntersectionIndex; FirstIntersectionIndex < WorkingCells[Index].Faces[CurrentFace].NumVerts; FirstIntersectionIndex++)
    {
        const vec3 fromVert = WorkingCells[Index].Faces[CurrentFace].Verts[FirstIntersectionIndex];
        const vec3 toVert = WorkingCells[Index].Faces[CurrentFace].Verts[(FirstIntersectionIndex +1) % WorkingCells[Index].Faces[CurrentFace].NumVerts];

        const vec3 lineDir = toVert - fromVert;
        vec3 intersectionPoint;
        const bool bDoesLineIntersect = GetIntersectionPoint(Center, Normal, fromVert, lineDir, intersectionPoint);
        if (bDoesLineIntersect)
        {
            const bool bIsIntersectionNextVertex = AlmostEqual(intersectionPoint, toVert, 0.0001);
            if (bIsIntersectionNextVertex)
            {
                //Add the next vert and the next next vert. Dont functionise this, as this program needs to reduce temeporary memeory usagae
                //As such, copying and local variables have been reduced as much as possible
                TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = toVert;
                TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
                TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = WorkingCells[Index].Faces[CurrentFace].Verts[(FirstIntersectionIndex + 2) % WorkingCells[Index].Faces[CurrentFace].NumVerts];
                TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
                FirstIntersectionIndex = (FirstIntersectionIndex + 2) % WorkingCells[Index].Faces[CurrentFace].NumVerts;

            }
            else
            {
                //Add intersection point then the next vert, as if the intersection point is not the next vert,
                //it means it lies somewhere between from vert and to vert 
                TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = intersectionPoint;
                TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
                TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = toVert;
                TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
                FirstIntersectionIndex = (FirstIntersectionIndex + 1) % WorkingCells[Index].Faces[CurrentFace].NumVerts;
            }
            FirstIntersection = intersectionPoint;
            break;
        }
    }
}
uint GetAllVertsUntillSecondIntersection(const in vec3 Normal, const in vec3 Center, const in uint ToClip, const in uint FirstIntersectionIndex, out vec3 SecondIntersection, const in uint Index)
{
    uint secondIntersectionIndex = 0;
    for (secondIntersectionIndex = FirstIntersectionIndex; secondIntersectionIndex <  WorkingCells[Index].Faces[ToClip].NumVerts; secondIntersectionIndex++)
    {
        const vec3 fromVert =  WorkingCells[Index].Faces[ToClip].Verts[secondIntersectionIndex];
        const vec3 toVert =  WorkingCells[Index].Faces[ToClip].Verts[(secondIntersectionIndex + 1) %  WorkingCells[Index].Faces[ToClip].NumVerts];

        const vec3 lineDir = toVert - fromVert;
        vec3 intersectionPoint;
        const bool bDoesLineIntersect = GetIntersectionPoint(Center, Normal, fromVert, lineDir, intersectionPoint);

        if (bDoesLineIntersect)
        {
            TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = intersectionPoint;
            TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
            SecondIntersection = intersectionPoint;
            secondIntersectionIndex++;
            break;
        }
        TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = toVert;
        TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
    }
    return secondIntersectionIndex;
}
bool isNearlyZero(const in double X)
{
    return X < 1e-6 && X > -1e-6;
}

bool IsPointInPolyhedra(const in vec3 Normal, const in uint Index, const in vec3 Center)
{
    for (uint i = 0; i < TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts; i++)
    {
        //if the dot from the center to any of the current verts is aligned with the normal, it is outside the current cell
        const float d = dot(TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[i] - Center, Normal);
        if (d > 0 && !isNearlyZero(d))
        {
            return false;
        }
    }
    return true;
}

void GetFaceReversed(const in uint ToClip, const in uint Index, const in uint FirstIntersectionIndex,
const in vec3 FirstIntersection, const in vec3 SecondIntersection, const in uint SecondInterectionIndex)
{
    TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts = 0;
    if (SecondIntersection !=  WorkingCells[Index].Faces[ToClip].Verts[SecondInterectionIndex %  WorkingCells[Index].Faces[ToClip].NumVerts])
    {
        TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = SecondIntersection;
        TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
    }
    //get the reverse verts, so instead of from the first intersection to second, you start at the second and get every vert until the first
    vec3 from;
    for (uint i = SecondInterectionIndex; i %  WorkingCells[Index].Faces[ToClip].NumVerts != FirstIntersectionIndex; i++)
    {
        from =  WorkingCells[Index].Faces[ToClip].Verts[i %  WorkingCells[Index].Faces[ToClip].NumVerts];
        const vec3 to =  WorkingCells[Index].Faces[ToClip].Verts[(i+1) %  WorkingCells[Index].Faces[ToClip].NumVerts];
        if (AlmostEqual(from, to, 0.0001)) continue;
        TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = from;
        TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
    }
    if (!AlmostEqual(from, FirstIntersection, 0.00001))
    {
        TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts] = FirstIntersection;
        TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts++;
    }

}

void ClipFacebyFace(const in uint ToClip, const in vec3 Center,const in uint Index, const in vec3 Normal)
{
    uint firstIntersectionIndex = 0;
    vec3 firstIntersection;
    GetFirstIntersection(Normal, Center, ToClip, firstIntersectionIndex, firstIntersection, Index);
    //If there is no first intersection
    if (TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts == 0)
    {
        //If any of the points are on the normal facing side of the plane, the face is discarded, else keep it 
        for (uint i = 0; i < WorkingCells[Index].Faces[ToClip].NumVerts; i++)
        {
            float d = dot(Normal, WorkingCells[Index].Faces[ToClip].Verts[i] - Center);
            if (d <= 0)
            {
                TempCells[Index].Faces[TempCells[Index].NumFaces] =  WorkingCells[Index].Faces[ToClip];
                return;
            }
        }
        return;
    }
    vec3 secondIntersection;
    uint secondIntersectionIndex = GetAllVertsUntillSecondIntersection(Normal, Center, ToClip, firstIntersectionIndex, secondIntersection, Index);
    //There are two possible shapes, as we are going from the first intersection untill the second.
    //If the point is not contained in the first shape, we need to get the second shape by continuing from the second intersection,
    //until we wrap round to the first intersection
    if (!IsPointInPolyhedra(Normal, Index, Center))
    {
        GetFaceReversed(ToClip, Index, firstIntersectionIndex, firstIntersection, secondIntersection, secondIntersectionIndex);
    }
    //As the shape is cut by a plane, we need to add a face for the cut, to ensure the shape remains convex
    IntersectFaces[Index].Verts[IntersectFaces[Index].NumVerts] = firstIntersection;
    IntersectFaces[Index].NumVerts++;
    IntersectFaces[Index].Verts[IntersectFaces[Index].NumVerts] = secondIntersection;
    IntersectFaces[Index].NumVerts++;

}

void GetPlaneAxis(const in vec3 Normal, out vec3 T, out vec3 U)
{
    vec3 Up = vec3(0, 1, 0);
    if (abs(dot(Normal, Up)) > 0.99f) Up = vec3(1, 0, 0);
    U = normalize(cross(Normal, Up));
    T = cross(Normal, U);
}

void OrderByAngle(inout Face InFace, const in vec3 Center, const in vec3 Normal)
{
    vec3 t, u;
    GetPlaneAxis(Normal, t, u);

    float angles[40];
    for (uint i = 0; i < InFace.NumVerts; i++)
    {
        const vec3 d = InFace.Verts[i] - Center;
        const float x = dot(d, u);
        const float y = dot(d, t);
        angles[i] = atan(y, x);
    }
    Face newFace;
    newFace.NumVerts = 0;
    float nextAngle = 99999;//Dummy number
    uint nextAngleIndex;
    while (newFace.NumVerts < InFace.NumVerts)
    {
        for (uint i = 0; i < InFace.NumVerts; i++)
        {
            if (angles[i] <= nextAngle)
            {
                nextAngle = angles[i];
                nextAngleIndex = i;
            }
        }
        newFace.Verts[newFace.NumVerts] = InFace.Verts[nextAngleIndex];
        newFace.NumVerts++;
        //Mark this angle as completed by setting it to a number that will never be reached
        angles[nextAngleIndex] = 99999;
        nextAngle = 9999;
    }

    InFace = newFace;
}
bool Contains(const in vec3 Item, const in Face InFace)
{
    for (uint i = 0; i < InFace.NumVerts; i++)
    {
        if (AlmostEqual(InFace.Verts[i], Item, 0.00001)) return true;
    }
    return false;
}

void RemoveDuplicates(const in uint Index)
{
    Face newFace;
    newFace.NumVerts = 0;
    for (uint i = 0; i < TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts; i++)
    {
        if (Contains(TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[i], newFace)) continue;

        newFace.Verts[newFace.NumVerts] =TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[i];
        newFace.NumVerts++;
    }
    TempCells[Index].Faces[TempCells[Index].NumFaces] = newFace;

}

void RemoveIntersectDuplicates(const in uint Index)
{
    //Need seperate functions for the intersect face to reduce temporary copies
    Face newFace;
    newFace.NumVerts = 0;
    for (uint i = 0; i < IntersectFaces[Index].NumVerts; i++)
    {
        if (Contains(IntersectFaces[Index].Verts[i], newFace)) continue;

        newFace.Verts[newFace.NumVerts] = IntersectFaces[Index].Verts[i];
        newFace.NumVerts++;
    }
    IntersectFaces[Index] = newFace;

}

void RemoveAt(const in uint FaceIndex, const in uint Index)
{
    TempCells[FaceIndex].Faces[TempCells[FaceIndex].NumFaces].NumVerts--;
    for (uint i = Index; i < TempCells[FaceIndex].Faces[TempCells[FaceIndex].NumFaces].NumVerts; i++)
    {
        TempCells[FaceIndex].Faces[TempCells[FaceIndex].NumFaces].Verts[i] = TempCells[FaceIndex].Faces[TempCells[FaceIndex].NumFaces].Verts[(i+1)];
    }
}

bool IsAlmostEqual(const in vec3 A, const in vec3 B)
{
    vec3 dif= A - B;

    bool less = dif.x < 1e-6 && dif.y < 1e-6 && dif.z < 1e-6;
    bool more = dif.x > -1e-6 && dif.y > -1e-6 && dif.z > -1e-6;

    return less && more;
}

void RemovePointsTooNear(const in uint Index)
{
    //If a point is too close to another point, there isnt a reason to contain them, thus they are removed.
    for (uint i = 0; i < TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts; i++)
    {
        if (IsAlmostEqual(TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[i], TempCells[Index].Faces[TempCells[Index].NumFaces].Verts[(i+1) % TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts]))
        {
            RemoveAt(Index, i);
        }
    }
}

void IntersectRemoveAt(const in uint FaceIndex, const in uint Index)
{
    IntersectFaces[FaceIndex].NumVerts--;
    for (uint i = Index; i < IntersectFaces[FaceIndex].NumVerts; i++)
    {
        IntersectFaces[FaceIndex].Verts[i] = IntersectFaces[FaceIndex].Verts[(i+1)];
    }
}


void RemoveIntersectPointsTooNear(const in uint Index)
{
    //If a point is too close to another point, there isnt a reason to contain them, thus they are removed.
    for (uint i = 0; i < IntersectFaces[Index].NumVerts; i++)
    {
        if (IsAlmostEqual(IntersectFaces[Index].Verts[i], IntersectFaces[Index].Verts[(i+1) % IntersectFaces[Index].NumVerts]))
        {
            IntersectRemoveAt(Index, i);
        }
    }
}

vec3 GetPlaneCenter(const in Face Plane)
{
    vec3 center = vec3(0, 0, 0);
    for (uint i = 0; i < Plane.NumVerts; i++)
    {
        center += Plane.Verts[i];
    }
    return center / Plane.NumVerts;
}

void ClipCellByFace(const in uint Index, const in vec3 Center, const in vec3 Normal)
{
    TempCells[Index].NumFaces = 0;
    IntersectFaces[Index].NumVerts = 0;
    //Clip each face by the plane, then add the intersect face if neccessary
    for (uint i = 0; i <  WorkingCells[Index].NumFaces; i++)
    {
        TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts = 0;
        ClipFacebyFace(i, Center, Index, Normal);

        if (TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts < 3) continue;

        RemoveDuplicates(Index);

        if (TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts < 3)
        {
            if (IntersectFaces[Index].NumVerts < 2) IntersectFaces[Index].NumVerts == 0;
            else IntersectFaces[Index].NumVerts -= 2;
            continue;
        }

        RemovePointsTooNear(Index);

        if (TempCells[Index].Faces[TempCells[Index].NumFaces].NumVerts < 3) 
        {
            if (IntersectFaces[Index].NumVerts < 2) IntersectFaces[Index].NumVerts == 0;
            else IntersectFaces[Index].NumVerts -= 2;
            continue;
        }

        OrderByAngle(TempCells[Index].Faces[TempCells[Index].NumFaces], GetPlaneCenter(TempCells[Index].Faces[TempCells[Index].NumFaces]), Normal);

        TempCells[Index].NumFaces++;
    }
    if (IntersectFaces[Index].NumVerts >= 3)
    {
        OrderByAngle(IntersectFaces[Index], Center, Normal);

        RemoveIntersectDuplicates(Index);

        RemoveIntersectPointsTooNear(Index);

        if (IntersectFaces[Index].NumVerts >= 3)
        {
            TempCells[Index].Faces[TempCells[Index].NumFaces] = IntersectFaces[Index];
            TempCells[Index].NumFaces++;
        }
    }

    WorkingCells[Index] = TempCells[Index];
}
bool Contains(const in vec3 Item, const in uint CellIndex, inout uint Index)
{

    for (uint i = 0; i < ClippedCells[CellIndex].NumVerts; i++)
    {
        if (AlmostEqual(ClippedCells[CellIndex].Verts[i], Item, 0.00001))
        {
            Index = i;
            return true;
        }
    }
    return false;
}




vec3 GetPlaneNormal(const in Face Plane, const in vec3 Center)
{
    vec3 normal = vec3(0, 0, 0);
    for (uint i = 0; i < Plane.NumVerts; i++)
    {
        const vec3 current = Plane.Verts[i];
        const vec3 next = Plane.Verts[(i+1) % Plane.NumVerts];

        normal.x += (current.y - next.y) * (current.z + next.z);
        normal.y += (current.z - next.z) * (current.x + next.x);
        normal.z += (current.x - next.x) * (current.y + next.y);
    }
    return normalize(normal);
}

Box CreateBox(const in uint CellIndex)
{
    Box box;
    box.Min = vec3(1.0 / 0.0, 1.0 / 0.0, 1.0 / 0.0);
    box.Max = vec3(-1.0 / 0.0, -1.0 / 0.0, -1.0 / 0.0);
    
    for (uint i = 0; i < CutCells[CellIndex].NumFaces; i++)
    {
        for (uint j = 0; j < CutCells[CellIndex].Faces[i].NumVerts; j++)
        {
            box.Min = min(box.Min, CutCells[CellIndex].Faces[i].Verts[j]);
            box.Max = max(box.Max, CutCells[CellIndex].Faces[i].Verts[j]);
        }
    }
    
    return box;
}

bool IsBoxIntersectingBox(const in Box InBox, const uint TetIndex)
{
    Box box;
    box.Min = vec3(1.0 / 0.0, 1.0 / 0.0, 1.0 / 0.0);
    box.Max = vec3(-1.0 / 0.0, -1.0 / 0.0, -1.0 / 0.0);
    
    //Create a bounding box for the tet
    for (uint i = 0; i < 4; i++)
    {
        for (uint j = 0; j < 3; j++)
        {
            box.Min = min(box.Min, Tets[TetIndex].Faces[i].Verts[j]);
            box.Max = max(box.Max,  Tets[TetIndex].Faces[i].Verts[j]);
        }
    }
    return all(lessThanEqual(InBox.Min, box.Max)) &&
    all(greaterThanEqual(InBox.Max, box.Min));
    
}

void PopulateCell(const uint TetIndex, uint CellIndex)
{
    //Convert tet to cell
    WorkingCells[CellIndex].NumFaces = 4;
    for (uint i = 0; i < 4; i++)
    {
        WorkingCells[CellIndex].Faces[i].NumVerts = 3;
        for (uint j = 0; j < 3; j++)
        {
            WorkingCells[CellIndex].Faces[i].Verts[j] = Tets[TetIndex].Faces[i].Verts[j];
        }
    }
}

void AddOrMakeInd(const in vec3 Vert, const uint CellIndex)
{
    uint index;
    if (Contains(Vert, CellIndex, index))
    {
        ClippedCells[CellIndex].Inds[ClippedCells[CellIndex].NumInds] = index;
        ClippedCells[CellIndex].NumInds++;
    }
    else
    {
        ClippedCells[CellIndex].Inds[ClippedCells[CellIndex].NumInds] = ClippedCells[CellIndex].NumVerts;
        ClippedCells[CellIndex].NumInds++;
        ClippedCells[CellIndex].Verts[ClippedCells[CellIndex].NumVerts] = Vert;
        ClippedCells[CellIndex].NumVerts++;
    }
}

void AppendCell(const in uint CellIndex)
{
    for (uint i = 0; i < WorkingCells[CellIndex].NumFaces; i++)
    {
        //Fan triangulation
        for (uint j = 1; j + 1< WorkingCells[CellIndex].Faces[i].NumVerts; j++)
        {
            AddOrMakeInd(WorkingCells[CellIndex].Faces[i].Verts[0], CellIndex);
            AddOrMakeInd(WorkingCells[CellIndex].Faces[i].Verts[j], CellIndex);
            AddOrMakeInd(WorkingCells[CellIndex].Faces[i].Verts[j+1], CellIndex);
        }
    }
}
void ClipCellByFaces(const in uint Index)
{
    //Get cell center
    vec3 center = vec3(0, 0, 0);
    for (uint i = 0; i < CutCells[Index].NumFaces; i++)
    {
        center += GetPlaneCenter(CutCells[Index].Faces[i]);
    }
    center /= CutCells[Index].NumFaces;
    
    for (uint i = 0; i < CutCells[Index].NumFaces; i++)
    {
        if (WorkingCells[Index].NumFaces == 0) return;
        
        vec3 normal = GetPlaneNormal(CutCells[Index].Faces[i], center);
        vec3 planeCenter = GetPlaneCenter(CutCells[Index].Faces[i]);
        //Reverse the normal if its not outward facing
        if (!isNearlyZero(dot(normal, center - planeCenter)) && dot(normal, center - planeCenter) >= 0) normal = -normal;
        
        if (isNearlyZero(normal.x) && isNearlyZero(normal.y) && isNearlyZero(normal.z)) continue;
        
        ClipCellByFace(Index, planeCenter, normal);

        for (uint j = 0; j < WorkingCells[Index].NumFaces; j++)
        {
            OrderByAngle(WorkingCells[Index].Faces[j], GetPlaneCenter(WorkingCells[Index].Faces[j]), normal);
        }
    }
}

void main()
{
    uint index = gl_GlobalInvocationID.x;

    if (index >= NumCells) return;
    
    Box box = CreateBox(index);
    
    ClippedCells[index].NumVerts = 0;
    ClippedCells[index].NumInds = 0;
    
    for (uint i = 0; i < NumTets; i++)
    {
        //AABB test, if its not in the bounding box, its not intersecting
        if (!IsBoxIntersectingBox(box, i)) continue;
        
        PopulateCell(i, index);
        
        ClipCellByFaces(index);
        
        if (WorkingCells[index].NumFaces == 0) continue;
        
        AppendCell(index);
        
    }
    if (ClippedCells[index].NumInds == 0) return;
    atomicAdd(NumCellsCut, 1);

}
